- include_vars: "bigip_pool_vars.yml"

- name: Create the pool
  bigip_pool:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    name: "{{ item[0] }}"
    validate_certs: "false"
    state: "absent"
    monitors:
      - "{{ item[1] }}"
  with_nested:
    - "{{ name | default(['pool1']) }}"
    - "{{ monitors | default(['/Common/http_head_f5']) }}"
  delegate_to: localhost
