- name: Configure BigIP
  hosts: aws_hosts
  connection: local

  tasks:
      - name: Add a new node member1
        bigip_node:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            host: "10.0.2.167"
            name: "member1"
            validate_certs: "false"
            state: "present"
            monitors:
              - /Common/icmp

      - name: Create the pool1 pool
        bigip_pool:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            name: "pool1"
            validate_certs: "false"
            monitors:
              - /Common/http_head_f5

      - name: Add members into pool1
        bigip_pool_member:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            state: "present"
            host: "{{ item }}"
            pool: "pool1"
            port: "8080"
            validate_certs: "false"
        with_items:
            - member1

      - name: Intermediate processing
        debug:
            msg: "Upgrade some software"

      - name: More intermediate processing
        debug:
            msg: "Install some configuration"

      - name: Add the iRule contained in the static file bodgeit-rewrite.tcl to the LTM module
        bigip_irule:
            module: "ltm"
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            name: "Bodgeit_Rewrite"
            src: "bodgeit-rewrite.tcl"
            validate_certs: "no"

      - name: Create a VIP
        bigip_virtual_server:
            server: "{{ inventory_hostname }}"
            description: "foo-vip"
            destination: "10.0.2.183"
            user: "{{username}}"
            password: "{{password}}"
            name: "vip-1"
            pool: "pool1"
            port: "80"
            snat: "Automap"
            all_profiles:
                - "http"
            all_rules:
                - "Bodgeit_Rewrite"
            validate_certs: "no"
