---
- name: Create partition foo using the default route domain
  bigip_partition:
    name: "{{ partition_name | default(['foo']) }}"
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    validate_certs: "no"
  delegate_to: localhost
...
