---
- name: Set NTP servers
  bigip_device_ntp:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    ntp_servers:
        - 'time.apple.com' 
        - 'time.nist.gov' 
    validate_certs: "no"
  delegate_to: localhost
...
