---
- name: set fact timezone
  set_fact:
    timezone: "America/New_York"

- name: Set timezone
  bigip_device_ntp:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    timezone: "{{ timezone }}"
    validate_certs: "no"
  delegate_to: localhost
...
