- include_vars: "bigip_device_dns_vars.yml"

- name: Set the DNS settings on the BIG-IP
  bigip_device_dns:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    name_servers:
        - "{{ item[0] }}"
    search:
        - "{{ item[1] }}"
    validate_certs: "no"
  with_nested:
    - "{{ name_servers }}"
    - "{{ search_domains }}"
  delegate_to: localhost
