---
- include_vars: "bigip_node_vars.yml"

- name: Remove a new node
  bigip_node:
    server: "{{ inventory_hostname }}"
    user: "{{username}}"
    password: "{{password}}"
    name: "{{ item[0] }}"
    validate_certs: "false"
    state: "absent"
    monitors:
      - "{{ item[1] }}"
  with_nested:
    - "{{ name | default(['member1']) }}"
    - "{{ monitors | default(['/Common/icmp']) }}"
  delegate_to: localhost
...
