---
  - name: Get all of the facts from my BIG-IP
    bigip_facts:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      include: "address_class,certificate,client_ssl_profile,device,device_group,interface,key,node,pool,provision,rule,self_ip,software,system_info,traffic_group,trunk,virtual_address,virtual_server,vlan"
      validate_certs: "false"

  - name: Mention the Self IP
    debug:
      msg: "I have self IP {{ self_ip['/Common/10.0.1.10'].address }}"

  - name: Mention the software
    debug:
      msg: "I have software version {{ software[0].version }}"

  - name: Send notification message via Slack
    slack:
      token: "xoxp-31953449971-121800067186-186543574213-548bd47fd08eba5bb9d99b422114ef08" 
      msg: '{{ inventory_hostname }} completed'
    delegate_to: localhost
