---
  - name: Get all of the facts from my BIG-IP
    bigip_facts:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      include: "address_class,certificate,client_ssl_profile,device,device_group,interface,key,node,pool,provision,rule,self_ip,software,system_info,traffic_group,trunk,virtual_address,virtual_server,vlan"
      validate_certs: "false"

  - name: Mention the Self IP
    debug:
      msg: "I have self IP {{ self_ip['/Common/10.0.1.10'].address }}"

  - name: Mention the software
    debug:
      msg: "I have software version {{ software[0].version }}"
