- include_vars: "bigip_pool_vars.yml"

- name: Create the pool
  bigip_pool:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    name: "{{ item[0] | default('pool1') }}"
    validate_certs: "false"
    monitors:
      - {{ item[1] | default('/Common/http_head_f5') }}"
    with_nested:
      - "{{ name | default([]) }}"
      - "{{ monitors | default([]) }}"
  delegate_to: localhost
