- name: Create Self IP
  bigip_selfip:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      address: "10.10.10.10"
      name: "self1"
      netmask: "255.255.255.0"
      vlan: "vlan1"
      validate_certs: "no"
  delegate_to: localhost

- name: Create Self IP with a Route Domain
  bigip_selfip:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      name: "self2"
      address: "10.10.10.10"
      netmask: "255.255.255.0"
      vlan: "net1"
      route_domain: "10"
      allow_service: "default"
      validate_certs: "no"
  delegate_to: localhost

- name: Delete Self IP
  bigip_selfip:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      name: "self1"
      state: "absent"
      validate_certs: "no"
  delegate_to: localhost

- name: Allow management web UI to be accessed on this Self IP
  bigip_selfip:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      name: "self1"
      state: "absent"
      validate_certs: "no"
      allow_service:
          - "tcp:443"
  delegate_to: localhost

- name: Allow HTTPS and SSH access to this Self IP
  bigip_selfip:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      name: "self1"
      state: "absent"
      validate_certs: "no"
      allow_service:
          - "tcp:443"
          - "tpc:22"
  delegate_to: localhost

- name: Allow all services access to this Self IP
  bigip_selfip:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      name: "self1"
      state: "absent"
      validate_certs: "no"
      allow_service:
          - all
  delegate_to: localhost

- name: Allow only GRE and IGMP protocols access to this Self IP
  bigip_selfip:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      name: "self1"
      state: "absent"
      validate_certs: "no"
      allow_service:
          - gre:0
          - igmp:0
  delegate_to: localhost

- name: Allow all TCP, but no other protocols access to this Self IP
  bigip_selfip:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      name: "self1"
      state: "absent"
      validate_certs: "no"
      allow_service:
          - tcp:0
  delegate_to: localhost
