- include_vars: "bigip_pool_member_vars.yml"


- name: Add members into a pool
  bigip_pool_member:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    host: "{{ item }}"
    pool: "{{ item[0] | default('pool1') }}"
    port: "{{ item[1] | default('8080') }}"
    state: "present"
    validate_certs: "false"
  with_items:
    - member1
  with_nested:
    - "{{ pool | default([]) }}"
    - "{{ port | default([]) }}"
  delegate_to: localhost
