- name: Add members into pool1
  bigip_pool_member:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    state: "present"
    host: "{{ item }}"
    pool: "pool1"
    port: "8080"
    validate_certs: "false"
  with_items:
    - member1
  delegate_to: localhost
