- include_vars: "bigip_pool_member_vars.yml"

- name: Add members into a pool
  bigip_pool_member:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    host: "{{ item[0] | default('member1') }}"
    pool: "{{ item[1] | default('pool1') }}"
    port: "{{ item[2] | default('8080') }}"
    state: "present"
    validate_certs: "false"
  with_nested:
    - "{{ host | default([]) }}"
    - "{{ pool | default([]) }}"
    - "{{ port | default([]) }}"
  delegate_to: localhost
