---
- include_vars: "bigip_pool_member_vars.yml"

- name: Manage members in a pool
  bigip_pool_member:
    server: "{{ inventory_hostname }}"
    user: "{{ username }}"
    password: "{{ password }}"
    host: "{{ item[0] }}"
    pool: "{{ item[1] }}"
    port: "{{ item[2] }}"
    state: "{{ state }}"
    validate_certs: "false"
  with_nested:
    - "{{ host | default(['member1']) }}"
    - "{{ pool | default(['pool1']) }}"
    - "{{ port | default(['8080']) }}"
  delegate_to: localhost
...
