- include_vars: "bigip_node_vars.yml"

- name: Add a new node
  bigip_node:
    server: "{{ inventory_hostname }}"
    user: "{{username}}"
    password: "{{password}}"
    host: "{{ item[0] }}"
    name: "{{ item[1] }}"
    validate_certs: "false"
    state: "present"
    monitors:
      - "{{ item[2] }}"
  with_nested:
    - "{{ host | default(['member1']) }}"
    - "{{ name | default(['10.0.2.167']) }}"
    - "{{ monitors | default(['/Common/icmp']) }}"
  delegate_to: localhost
